import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL,
});
const prisma = new PrismaClient({ adapter });

const categories = [
  {
    name: "Cotton Sarees",
    slug: "cotton-sarees",
    description: "Breathable handloom and mill cotton sarees for everyday elegance.",
  },
  {
    name: "Silk Cotton Sarees",
    slug: "silk-cotton-sarees",
    description: "Traditional silk cotton weaves with rich zari borders, perfect for festive wear.",
  },
  {
    name: "Printed Sarees",
    slug: "printed-sarees",
    description: "Contemporary marbled and abstract prints paired with classic zari borders.",
  },
];

const products = [
  {
    folder: "1",
    name: "Olive Handloom Cotton Saree with Temple Border",
    slug: "olive-handloom-cotton-temple-border",
    description:
      "A soft handloom cotton saree in earthy olive, finished with a coral-red temple (zigzag) border and a rich maroon pallu woven with floral motifs. Lightweight and breathable — ideal for daily wear and office.",
    fabric: "Handloom Cotton",
    color: "Olive Green",
    price: 189900,
    compareAtPrice: 229900,
    category: "cotton-sarees",
    featured: true,
    images: 3,
  },
  {
    folder: "2",
    name: "Emerald Green Cotton Silk Saree with Zari Butta",
    slug: "emerald-green-cotton-silk-zari-butta",
    description:
      "A vibrant emerald green cotton silk saree scattered with golden zari butta motifs, framed by a bold red temple border and finished with contrast red-and-green tassels.",
    fabric: "Cotton Silk",
    color: "Emerald Green",
    price: 219900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 4,
  },
  {
    folder: "3",
    name: "Maroon Gold Checked Silk Cotton Saree",
    slug: "maroon-gold-checked-silk-cotton",
    description:
      "A regal maroon and gold checked silk cotton saree with a heavily woven zari pallu, paired with a marbled orange-green contrast petticoat piece. A statement pick for weddings and festive occasions.",
    fabric: "Silk Cotton",
    color: "Maroon",
    price: 249900,
    compareAtPrice: 279900,
    category: "silk-cotton-sarees",
    featured: true,
    images: 4,
  },
  {
    folder: "4",
    name: "Maroon Zari Saree with Abstract Multicolor Pallu",
    slug: "maroon-zari-abstract-multicolor-pallu",
    description:
      "A striking cotton saree pairing a hand-marbled multicolor abstract pallu with a densely woven maroon-and-gold zari body. Contemporary art meets traditional weaving.",
    fabric: "Cotton",
    color: "Maroon Multicolor",
    price: 179900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 4,
  },
  {
    folder: "5",
    name: "Mustard Marble-Print Saree with Maroon Zari Border",
    slug: "mustard-marble-print-maroon-zari-border",
    description:
      "A mustard and green marble-print pallu flows into a deep maroon zari body woven with a temple motif, creating a saree that feels both artistic and traditional.",
    fabric: "Cotton",
    color: "Mustard",
    price: 179900,
    compareAtPrice: 199900,
    category: "printed-sarees",
    featured: false,
    images: 4,
  },
  {
    folder: "6",
    name: "Black Checked Cotton Saree with Peacock Pallu",
    slug: "black-checked-cotton-peacock-pallu",
    description:
      "A classic black cotton saree with a fine gold checked weave, finished with a rich mustard pallu depicting woven peacock motifs. Timeless and versatile.",
    fabric: "Handloom Cotton",
    color: "Black",
    price: 199900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: true,
    images: 3,
  },
  {
    folder: "7",
    name: "Mustard Gold Jacquard Cotton Saree",
    slug: "mustard-gold-jacquard-cotton",
    description:
      "A refined mustard cotton saree with an allover self-jacquard motif, offering understated texture and shine — an easy everyday-to-office saree.",
    fabric: "Cotton",
    color: "Mustard",
    price: 169900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
  },
  {
    folder: "9",
    name: "Mustard Cotton Saree with Maroon Peacock Border",
    slug: "mustard-cotton-maroon-peacock-border",
    description:
      "A warm mustard handloom cotton saree with woven gold stripes and a deep maroon border showcasing intricate peacock medallions — a festive favourite.",
    fabric: "Handloom Cotton",
    color: "Mustard",
    price: 189900,
    compareAtPrice: 209900,
    category: "cotton-sarees",
    featured: true,
    images: 4,
  },
  {
    folder: "niy-1",
    name: "Olive Cotton Saree with Coral Lotus Motifs",
    slug: "olive-cotton-saree-with-coral-lotus-motifs",
    description:
      "An olive-green handloom cotton saree scattered with coral-red and slate lotus bunch motifs, framed by fine grey wave-stripe borders. Simple, everyday elegance.",
    fabric: "Handloom Cotton",
    color: "Olive Green",
    price: 169900,
    compareAtPrice: 199900,
    category: "cotton-sarees",
    featured: true,
    images: 3,
    ext: "png",
  },
  {
    folder: "niy-2",
    name: "Emerald Cotton Saree with Golden Lotus Butta",
    slug: "emerald-cotton-saree-with-golden-lotus-butta",
    description:
      "A vivid emerald cotton saree with gold-and-teal lotus butta motifs and a bold coral-red temple border, finished with orange tassels.",
    fabric: "Cotton",
    color: "Emerald Green",
    price: 179900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-3",
    name: "Maroon Zari Saree with Marbled Contrast Underskirt",
    slug: "maroon-zari-saree-with-marbled-contrast-underskirt",
    description:
      "A regal maroon and gold zari-woven saree with pillar motifs, paired with a hand-marbled orange-green contrast under-piece for a festive layered look.",
    fabric: "Silk Cotton",
    color: "Maroon",
    price: 189900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 5,
    ext: "png",
  },
  {
    folder: "niy-4",
    name: "Maroon Zari Saree with Abstract Marbled Pallu",
    slug: "maroon-zari-saree-with-abstract-marbled-pallu",
    description:
      "A hand-marbled multicolour abstract pallu flows into a densely woven maroon-and-gold zari body with temple motifs — contemporary art meeting traditional weaving.",
    fabric: "Cotton",
    color: "Maroon Multicolour",
    price: 199900,
    compareAtPrice: 229900,
    category: "printed-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-5",
    name: "Golden Marble-Print Saree with Maroon Zari Border",
    slug: "golden-marble-print-saree-with-maroon-zari-border",
    description:
      "A golden-orange marble-print pallu with sunburst motifs meets a deep maroon zari body woven with pagoda medallions.",
    fabric: "Cotton",
    color: "Golden Mustard",
    price: 209900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-6",
    name: "Black Checked Cotton Saree with Peacock Pallu",
    slug: "black-checked-cotton-saree-with-peacock-pallu",
    description:
      "A classic black cotton saree with a fine gold checked weave, finished with a mustard pallu woven with peacock motifs.",
    fabric: "Handloom Cotton",
    color: "Black",
    price: 219900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "png",
  },
  {
    folder: "niy-7",
    name: "Mustard Self-Jacquard Cotton Saree",
    slug: "mustard-self-jacquard-cotton-saree",
    description:
      "A refined mustard cotton saree with an allover self-jacquard motif offering understated texture and shine — easy everyday-to-office wear.",
    fabric: "Cotton",
    color: "Mustard",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "png",
  },
  {
    folder: "niy-9",
    name: "Mustard Cotton Saree with Maroon Peacock Roundels",
    slug: "mustard-cotton-saree-with-maroon-peacock-roundels",
    description:
      "A warm mustard handloom cotton saree with woven gold pinstripes and a maroon border showcasing peacock medallions.",
    fabric: "Handloom Cotton",
    color: "Mustard",
    price: 239900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: true,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-10",
    name: "Olive Cotton Saree with Maroon Floral Pallu",
    slug: "olive-cotton-saree-with-maroon-floral-pallu",
    description:
      "An olive-checked cotton body pairs with a maroon pallu woven with cream floral motifs and a coral-red inner stripe.",
    fabric: "Handloom Cotton",
    color: "Olive Green",
    price: 249900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-11",
    name: "Black Cotton Saree with Olive Peacock Border",
    slug: "black-cotton-saree-with-olive-peacock-border",
    description:
      "A black cotton saree with a fine gold grid weave, bordered by an olive-green pallu with woven gold peacock roundels.",
    fabric: "Cotton",
    color: "Black",
    price: 259900,
    compareAtPrice: 289900,
    category: "cotton-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-12",
    name: "Olive Green Cotton Saree with Rust Zari Border",
    slug: "olive-green-cotton-saree-with-rust-zari-border",
    description:
      "A soft olive cotton saree finished with a rust-orange zari border and fine grey wave trims — versatile daily wear.",
    fabric: "Cotton",
    color: "Olive Green",
    price: 269900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 2,
    ext: "png",
  },
  {
    folder: "niy-13",
    name: "Orange Cotton Saree with Navy Paisley Border",
    slug: "orange-cotton-saree-with-navy-paisley-border",
    description:
      "A bright orange cotton saree with grey chain-stripe weaves and a maroon-navy border carrying bold paisley medallions.",
    fabric: "Cotton",
    color: "Orange",
    price: 279900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 2,
    ext: "png",
  },
  {
    folder: "niy-14",
    name: "Beige Cotton Saree with Coral Floral Border",
    slug: "beige-cotton-saree-with-coral-floral-border",
    description:
      "A soft beige cotton saree hand-block printed with grey floral sprays, bordered by a coral floral vine and fine trellis print.",
    fabric: "Cotton",
    color: "Beige",
    price: 169900,
    compareAtPrice: 199900,
    category: "printed-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-15",
    name: "Sage Green Cotton Saree with Coral Lotus Motifs",
    slug: "sage-green-cotton-saree-with-coral-lotus-motifs",
    description:
      "A sage-green handloom cotton saree with coral-red and charcoal lotus bunch motifs bordered by fine wave stripes.",
    fabric: "Handloom Cotton",
    color: "Sage Green",
    price: 179900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 4,
    ext: "png",
  },
  {
    folder: "niy-16",
    name: "Rust Ikat Cotton Saree with Maroon Zari Border",
    slug: "rust-ikat-cotton-saree-with-maroon-zari-border",
    description:
      "A rust-brown cotton saree woven with a charcoal ikat diamond motif, framed by a maroon zari border with gold edging.",
    fabric: "Cotton",
    color: "Rust Brown",
    price: 189900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-17",
    name: "Slate Grey Cotton Saree with Gold Temple Border",
    slug: "slate-grey-cotton-saree-with-gold-temple-border",
    description:
      "A slate-grey cotton saree with a teal woven medallion pallu, a mustard-gold temple border trim, and scattered dark blue butta motifs.",
    fabric: "Cotton",
    color: "Slate Grey",
    price: 199900,
    compareAtPrice: 229900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-18",
    name: "Dusty Rose Cotton Saree with Silver Zari Stripes",
    slug: "dusty-rose-cotton-saree-with-silver-zari-stripes",
    description:
      "A dusty-rose cotton saree in soft pinstripes, finished with a shimmering silver zari border for understated festive wear.",
    fabric: "Cotton",
    color: "Dusty Rose",
    price: 209900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-19",
    name: "Silver Grey Zari-Striped Cotton Saree",
    slug: "silver-grey-zari-striped-cotton-saree",
    description:
      "A silver-grey cotton saree with metallic zari pinstripes running the length of the body — sleek and minimal.",
    fabric: "Cotton",
    color: "Silver Grey",
    price: 219900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-20",
    name: "Mint Green Cotton Saree with Silver Zari Border",
    slug: "mint-green-cotton-saree-with-silver-zari-border",
    description:
      "A refreshing mint-green cotton saree with a wide silver metallic stripe border, clean and contemporary.",
    fabric: "Cotton",
    color: "Mint Green",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-21",
    name: "Charcoal Grey Cotton Saree with Silver Pinstripes",
    slug: "charcoal-grey-cotton-saree-with-silver-pinstripes",
    description:
      "A charcoal-grey cotton saree finished with fine silver metallic pinstripes for a subtle shimmer.",
    fabric: "Cotton",
    color: "Charcoal Grey",
    price: 239900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-22",
    name: "Sage Green Cotton Saree with Gold Pinstripe Border",
    slug: "sage-green-cotton-saree-with-gold-pinstripe-border",
    description:
      "A sage-green cotton saree with a broad gold-and-white pinstripe border, easy to dress up or down.",
    fabric: "Cotton",
    color: "Sage Green",
    price: 249900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-23",
    name: "Taupe Cotton Saree with Maroon Tree-of-Life Border",
    slug: "taupe-cotton-saree-with-maroon-tree-of-life-border",
    description:
      "A taupe cotton saree bordered in deep maroon with a gold tree-of-life motif woven repeat — a timeless festive pick.",
    fabric: "Cotton",
    color: "Taupe",
    price: 259900,
    compareAtPrice: 289900,
    category: "silk-cotton-sarees",
    featured: true,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-24",
    name: "Cream Cotton Saree with Magenta Temple Border",
    slug: "cream-cotton-saree-with-magenta-temple-border",
    description:
      "A cream cotton saree with red-and-green pinstripes, edged in a magenta temple-pyramid border with gold circular motifs.",
    fabric: "Cotton",
    color: "Cream",
    price: 269900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-25",
    name: "Peach Cotton Saree with Brown-Gold Zari Border",
    slug: "peach-cotton-saree-with-brown-gold-zari-border",
    description:
      "A soft peach cotton saree finished with a deep brown-gold zari border carrying oval medallions and a black temple trim.",
    fabric: "Cotton",
    color: "Peach",
    price: 279900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-26",
    name: "Beige Cotton Saree with Olive-Brown Zari Pallu",
    slug: "beige-cotton-saree-with-olive-brown-zari-pallu",
    description:
      "A beige cotton saree with a black-dot trim, its pallu woven in olive and dark brown zari with a red temple pattern.",
    fabric: "Cotton",
    color: "Beige",
    price: 169900,
    compareAtPrice: 199900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-27",
    name: "Mustard Cotton Saree with Rust Temple Pallu",
    slug: "mustard-cotton-saree-with-rust-temple-pallu",
    description:
      "A mustard cotton saree with a scalloped dot trim, its pallu woven in rust-red temple triangles over a rich brown-gold zari border.",
    fabric: "Cotton",
    color: "Mustard",
    price: 179900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-28",
    name: "Crimson Cotton Saree with Green-Gold Zari Border",
    slug: "crimson-cotton-saree-with-green-gold-zari-border",
    description:
      "A crimson cotton saree bordered in forest green and gold florals, warm and festive.",
    fabric: "Cotton",
    color: "Crimson Red",
    price: 189900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-29",
    name: "Olive-Wine Ombre Cotton Saree with Gold Medallions",
    slug: "olive-wine-ombre-cotton-saree-with-gold-medallions",
    description:
      "An olive-to-wine ombre cotton saree bordered with gold circular medallions for a rich, layered colour transition.",
    fabric: "Cotton",
    color: "Olive-Wine",
    price: 199900,
    compareAtPrice: 229900,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-30",
    name: "Black-Brown Cotton Saree with Green Contrast Border",
    slug: "black-brown-cotton-saree-with-green-contrast-border",
    description:
      "A black-brown cotton saree with gold pinstripes and a temple-zigzag pallu, finished with a bright green contrast edge.",
    fabric: "Cotton",
    color: "Black Brown",
    price: 209900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-31",
    name: "Pistachio Green Cotton Saree with Elephant Motif Border",
    slug: "pistachio-green-cotton-saree-with-elephant-motif-border",
    description:
      "A pistachio-green cotton saree with a black woven border of marching elephants and florals, finished with a red edge trim.",
    fabric: "Cotton",
    color: "Pistachio Green",
    price: 219900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-32",
    name: "Deep Red Cotton Saree with Gold Floral Medallion Border",
    slug: "deep-red-cotton-saree-with-gold-floral-medallion-border",
    description:
      "A deep red cotton saree with an ornate dark-brown and gold floral medallion border for rich festive wear.",
    fabric: "Cotton",
    color: "Deep Red",
    price: 229900,
    compareAtPrice: 259900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-33",
    name: "Teal Cotton Saree with Maroon-Gold Figurine Pallu",
    slug: "teal-cotton-saree-with-maroon-gold-figurine-pallu",
    description:
      "A peacock-teal cotton saree with a maroon-gold pallu woven with dancing figurine motifs — a distinctive statement piece.",
    fabric: "Cotton",
    color: "Teal",
    price: 239900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-34",
    name: "Cream Cotton Saree with Brown-Gold Oval Medallion Border",
    slug: "cream-cotton-saree-with-brown-gold-oval-medallion-border",
    description:
      "A cream cotton saree with a black temple triangle trim and an ornate brown-gold border of oval medallions.",
    fabric: "Cotton",
    color: "Cream",
    price: 249900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-35",
    name: "Red Cotton Saree with Green-Gold Temple Border",
    slug: "red-cotton-saree-with-green-gold-temple-border",
    description:
      "A red cotton saree bordered with green-and-gold temple triangles and circular medallions — a bold festive classic.",
    fabric: "Cotton",
    color: "Red",
    price: 259900,
    compareAtPrice: 289900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-36",
    name: "Maroon Cotton Saree with Navy-Gold Elephant Procession Border",
    slug: "maroon-cotton-saree-with-navy-gold-elephant-procession-border",
    description:
      "A maroon cotton saree with a striking navy-and-gold border depicting a royal elephant-and-warrior procession.",
    fabric: "Cotton",
    color: "Maroon",
    price: 269900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-37",
    name: "Aubergine Cotton Saree with Red-Gold Medallion Border",
    slug: "aubergine-cotton-saree-with-red-gold-medallion-border",
    description:
      "A deep aubergine cotton saree finished with a red-and-gold ornate medallion border.",
    fabric: "Cotton",
    color: "Aubergine",
    price: 279900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-38",
    name: "Mustard Cotton Saree with Maroon Paisley Zari Border",
    slug: "mustard-cotton-saree-with-maroon-paisley-zari-border",
    description:
      "A mustard cotton saree bordered with a brown-maroon ornate paisley zari weave.",
    fabric: "Cotton",
    color: "Mustard",
    price: 169900,
    compareAtPrice: 199900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-39",
    name: "Ivory Cotton Saree with Charcoal Paisley Border",
    slug: "ivory-cotton-saree-with-charcoal-paisley-border",
    description:
      "An ivory cotton saree with an elegant charcoal-black woven paisley-and-floral border.",
    fabric: "Cotton",
    color: "Ivory",
    price: 179900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-40",
    name: "Mustard Cotton Saree with Aubergine-Gold Border",
    slug: "mustard-cotton-saree-with-aubergine-gold-border",
    description:
      "A mustard cotton saree finished with a dark aubergine-and-gold ornate medallion border.",
    fabric: "Cotton",
    color: "Mustard",
    price: 189900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-41",
    name: "Parrot Green Cotton Saree with Navy Crane Motif Border",
    slug: "parrot-green-cotton-saree-with-navy-crane-motif-border",
    description:
      "A parrot-green cotton saree with a maroon-brown border woven with navy blue flying crane motifs.",
    fabric: "Cotton",
    color: "Parrot Green",
    price: 199900,
    compareAtPrice: 229900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-42",
    name: "Olive Cotton Saree with Maroon-Gold Elephant Border",
    slug: "olive-cotton-saree-with-maroon-gold-elephant-border",
    description:
      "An olive-lime cotton saree bordered in maroon and gold with woven elephant and peacock motifs — rich and festive.",
    fabric: "Cotton",
    color: "Olive Green",
    price: 209900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-43",
    name: "Rust Brown Cotton Saree with Teal Floral Border",
    slug: "rust-brown-cotton-saree-with-teal-floral-border",
    description:
      "A rust-brown cotton saree with an unusual teal-green woven floral border for a distinctive colour contrast.",
    fabric: "Cotton",
    color: "Rust Brown",
    price: 219900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-44",
    name: "Maroon Cotton Saree with Mustard-Green Temple Border",
    slug: "maroon-cotton-saree-with-mustard-green-temple-border",
    description:
      "A maroon cotton saree finished with a mustard-and-green temple border and diamond lattice weave.",
    fabric: "Cotton",
    color: "Maroon",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-45",
    name: "Peach Cotton Saree with Brown-Gold Zari Border and Black Temple Trim",
    slug: "peach-cotton-saree-with-brown-gold-zari-border-and-black-temple-trim",
    description:
      "A peach cotton saree with a black temple triangle trim, finished with an ornate brown-gold zari border of leaf medallions.",
    fabric: "Cotton",
    color: "Peach",
    price: 239900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-46",
    name: "Beige Cotton Saree with Olive-Brown Zari Pallu and Red Pyramid Pattern",
    slug: "beige-cotton-saree-with-olive-brown-zari-pallu-and-red-pyramid-pattern",
    description:
      "A beige cotton saree with black-red dotted trim and an olive-dark-brown zari pallu carrying a red temple pyramid pattern.",
    fabric: "Cotton",
    color: "Beige",
    price: 249900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-47",
    name: "Mustard Cotton Saree with Rust Temple Pallu and Brown Border",
    slug: "mustard-cotton-saree-with-rust-temple-pallu-and-brown-border",
    description:
      "A mustard cotton saree with a dotted wave trim, its rust-red temple triangle pallu flowing into a dark brown zari border.",
    fabric: "Cotton",
    color: "Mustard",
    price: 259900,
    compareAtPrice: 289900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-48",
    name: "Crimson Cotton Saree with Forest Green-Gold Border",
    slug: "crimson-cotton-saree-with-forest-green-gold-border",
    description:
      "A bright crimson cotton saree bordered with a forest-green and gold floral zari weave.",
    fabric: "Cotton",
    color: "Crimson",
    price: 269900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-49",
    name: "Olive-Wine Ombre Cotton Saree with Gold Circular Border",
    slug: "olive-wine-ombre-cotton-saree-with-gold-circular-border",
    description:
      "An olive-green fading into deep wine, this ombre cotton saree is finished with a gold circular medallion border.",
    fabric: "Cotton",
    color: "Olive Wine",
    price: 279900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-50",
    name: "Black-Brown Cotton Saree with Green Edge and Zigzag Pallu",
    slug: "black-brown-cotton-saree-with-green-edge-and-zigzag-pallu",
    description:
      "A black-brown cotton saree with gold pinstripe borders and a temple zigzag pallu, edged in a bright green contrast trim.",
    fabric: "Cotton",
    color: "Black Brown",
    price: 169900,
    compareAtPrice: 199900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-51",
    name: "Cream Cotton Saree with Brown-Gold Border and Black Trim",
    slug: "cream-cotton-saree-with-brown-gold-border-and-black-trim",
    description:
      "A cream cotton saree with a black temple triangle trim and an ornate brown-gold oval-medallion border.",
    fabric: "Cotton",
    color: "Cream",
    price: 179900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-52",
    name: "Red Cotton Saree with Green-Gold Temple Border and Circular Medallions",
    slug: "red-cotton-saree-with-green-gold-temple-border-and-circular-medallions",
    description:
      "A red cotton saree bordered with green-gold temple triangles and rows of circular medallions.",
    fabric: "Cotton",
    color: "Red",
    price: 189900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-53",
    name: "Maroon Cotton Saree with Navy-Gold Royal Procession Border",
    slug: "maroon-cotton-saree-with-navy-gold-royal-procession-border",
    description:
      "A maroon cotton saree with a navy-and-gold woven border depicting an elephant-and-warrior royal procession — a true statement piece.",
    fabric: "Cotton",
    color: "Maroon",
    price: 199900,
    compareAtPrice: 229900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-54",
    name: "Aubergine Cotton Saree with Red-Gold Circular Medallion Border",
    slug: "aubergine-cotton-saree-with-red-gold-circular-medallion-border",
    description:
      "A deep aubergine-black cotton saree finished with a red-and-gold ornate circular medallion border.",
    fabric: "Cotton",
    color: "Aubergine",
    price: 209900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-55",
    name: "Mustard Cotton Saree with Maroon Paisley Border and Diamond Weave",
    slug: "mustard-cotton-saree-with-maroon-paisley-border-and-diamond-weave",
    description:
      "A mustard cotton saree bordered in brown-maroon with an ornate paisley and diamond zari weave.",
    fabric: "Cotton",
    color: "Mustard",
    price: 219900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-56",
    name: "Ivory Cotton Saree with Charcoal Paisley Border Weave",
    slug: "ivory-cotton-saree-with-charcoal-paisley-border-weave",
    description:
      "An ivory cotton saree finished with a fine charcoal-black woven paisley-and-vine border.",
    fabric: "Cotton",
    color: "Ivory",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-57",
    name: "Mustard Cotton Saree with Aubergine-Gold Ornate Border",
    slug: "mustard-cotton-saree-with-aubergine-gold-ornate-border",
    description:
      "A mustard cotton saree with a dark aubergine-and-gold ornate medallion border weave.",
    fabric: "Cotton",
    color: "Mustard",
    price: 239900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-58",
    name: "Parrot Green Cotton Saree with Navy Crane Border",
    slug: "parrot-green-cotton-saree-with-navy-crane-border",
    description:
      "A parrot-green cotton saree bordered in maroon-brown with woven navy blue crane motifs in flight.",
    fabric: "Cotton",
    color: "Parrot Green",
    price: 249900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-59",
    name: "Olive Green Cotton Saree with Maroon-Gold Elephant Weave",
    slug: "olive-green-cotton-saree-with-maroon-gold-elephant-weave",
    description:
      "An olive-lime cotton saree with a rich maroon-gold border woven with elephant and peacock motifs.",
    fabric: "Cotton",
    color: "Olive Green",
    price: 259900,
    compareAtPrice: 289900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-60",
    name: "Rust Brown Cotton Saree with Teal Floral Weave Border",
    slug: "rust-brown-cotton-saree-with-teal-floral-weave-border",
    description:
      "A rust-brown cotton saree with a striking teal-green woven floral border.",
    fabric: "Cotton",
    color: "Rust Brown",
    price: 269900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-61",
    name: "Maroon Cotton Saree with Mustard-Green Diamond Border",
    slug: "maroon-cotton-saree-with-mustard-green-diamond-border",
    description:
      "A maroon cotton saree finished with a mustard-and-green temple border over a fine diamond lattice weave.",
    fabric: "Cotton",
    color: "Maroon",
    price: 279900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-62",
    name: "Black-Gold Silk Saree with Red Diamond Pallu",
    slug: "black-gold-silk-saree-with-red-diamond-pallu",
    description:
      "A black-and-gold silk saree with an ornate leaf-medallion border, paired with a red diamond-lattice pallu for a bold festive finish.",
    fabric: "Silk Cotton",
    color: "Black Gold",
    price: 169900,
    compareAtPrice: 199900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-63",
    name: "Magenta Silk Saree with Teal-Gold Paisley Border",
    slug: "magenta-silk-saree-with-teal-gold-paisley-border",
    description:
      "A magenta silk saree with a dotted diamond weave, bordered in teal and gold with ornate paisley leaf motifs.",
    fabric: "Silk Cotton",
    color: "Magenta",
    price: 179900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-64",
    name: "Coral Pink Silk Saree with Gold Floral Border",
    slug: "coral-pink-silk-saree-with-gold-floral-border",
    description:
      "A coral-pink silk saree in a fine diamond-jacquard weave, finished with a wide gold floral zari border.",
    fabric: "Silk Cotton",
    color: "Coral Pink",
    price: 189900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-65",
    name: "Copper Zari Silk Saree with Sage-Gold Border",
    slug: "copper-zari-silk-saree-with-sage-gold-border",
    description:
      "A copper-toned zari silk saree with an ornate floral medallion pallu, paired with a sage-and-gold diamond lattice body.",
    fabric: "Silk Cotton",
    color: "Copper",
    price: 199900,
    compareAtPrice: 229900,
    category: "silk-cotton-sarees",
    featured: true,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-66",
    name: "Emerald Green Silk Saree with Gold Floral Lattice",
    slug: "emerald-green-silk-saree-with-gold-floral-lattice",
    description:
      "An emerald-green silk saree woven in a gold diamond-lattice with large floral medallions, finished with a plum-gold pallu border.",
    fabric: "Silk Cotton",
    color: "Emerald Green",
    price: 209900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-67",
    name: "Teal Green Silk Saree with Magenta Pallu Edge",
    slug: "teal-green-silk-saree-with-magenta-pallu-edge",
    description:
      "A teal-green silk saree in a gold diamond-lattice weave, finished with a rich magenta-and-gold pallu edge.",
    fabric: "Silk Cotton",
    color: "Teal Green",
    price: 219900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-68",
    name: "Dusty Rose Cotton Saree with Maroon-Gold Medallion Border",
    slug: "dusty-rose-cotton-saree-with-maroon-gold-medallion-border",
    description:
      "A dusty-rose cotton saree in fine gold pinstripes, bordered in maroon with woven gold medallions.",
    fabric: "Cotton",
    color: "Dusty Rose",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-69",
    name: "Taupe Checked Cotton Saree with Gold Peacock Border",
    slug: "taupe-checked-cotton-saree-with-gold-peacock-border",
    description:
      "A taupe checked cotton saree finished with a deep maroon-brown border woven with gold peacock motifs.",
    fabric: "Cotton",
    color: "Taupe",
    price: 239900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-70",
    name: "Mauve Checked Cotton Saree with Purple-Gold Elephant Border",
    slug: "mauve-checked-cotton-saree-with-purple-gold-elephant-border",
    description:
      "A mauve checked cotton saree bordered in deep purple and gold with woven elephant and floral motifs.",
    fabric: "Cotton",
    color: "Mauve",
    price: 249900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-71",
    name: "Marigold Crinkle Cotton Saree with Silver Lotus Border",
    slug: "marigold-crinkle-cotton-saree-with-silver-lotus-border",
    description:
      "A marigold-orange crinkle-textured cotton saree finished with a silver zari lotus-motif border.",
    fabric: "Cotton",
    color: "Marigold Orange",
    price: 259900,
    compareAtPrice: 289900,
    category: "printed-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-72",
    name: "Peacock Blue Batik Print Cotton Saree with Silver Border",
    slug: "peacock-blue-batik-print-cotton-saree-with-silver-border",
    description:
      "A peacock-blue and navy batik crackle-print cotton saree, framed by a shimmering silver zari floral border.",
    fabric: "Cotton",
    color: "Peacock Blue",
    price: 269900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: true,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-73",
    name: "Olive Batik Print Cotton Saree with Zari Border",
    slug: "olive-batik-print-cotton-saree-with-zari-border",
    description:
      "An olive-yellow batik crackle-print cotton saree bordered with a dark olive zari floral weave.",
    fabric: "Cotton",
    color: "Olive Yellow",
    price: 279900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-74",
    name: "Crimson Batik Print Cotton Saree with Silver Border",
    slug: "crimson-batik-print-cotton-saree-with-silver-border",
    description:
      "A crimson-and-cream batik crackle-print cotton saree with a maroon-silver zari floral border.",
    fabric: "Cotton",
    color: "Crimson",
    price: 169900,
    compareAtPrice: 199900,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-75",
    name: "Violet Batik Print Cotton Saree with Silver Border",
    slug: "violet-batik-print-cotton-saree-with-silver-border",
    description:
      "A violet batik crackle-print cotton saree edged in deep aubergine with a silver zari border.",
    fabric: "Cotton",
    color: "Violet",
    price: 179900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-76",
    name: "Beige-Wine Ombre Bandhani Print Cotton Saree",
    slug: "beige-wine-ombre-bandhani-print-cotton-saree",
    description:
      "A beige cotton saree dip-dyed into deep wine at the hem, overlaid with a bandhani-style diamond dot print and gold pinstripes.",
    fabric: "Cotton",
    color: "Beige Wine",
    price: 189900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-77",
    name: "Mustard-Black Ombre Bandhani Print Cotton Saree",
    slug: "mustard-black-ombre-bandhani-print-cotton-saree",
    description:
      "A mustard cotton saree dip-dyed to black at the crown, printed with bandhani dot tree motifs.",
    fabric: "Cotton",
    color: "Mustard Black",
    price: 199900,
    compareAtPrice: 229900,
    category: "printed-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-78",
    name: "Brown-Navy Checked Bandhani Print Cotton Saree",
    slug: "brown-navy-checked-bandhani-print-cotton-saree",
    description:
      "A brown-and-navy checked cotton saree printed with bandhani dot-circle motifs and a warm dip-dyed ombre edge.",
    fabric: "Cotton",
    color: "Brown Navy",
    price: 209900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-79",
    name: "Red Cotton Saree with Gold Diamond Lattice Weave",
    slug: "red-cotton-saree-with-gold-diamond-lattice-weave",
    description:
      "A bright red cotton saree with an allover gold diamond-lattice self-jacquard weave and a slim gold border.",
    fabric: "Cotton",
    color: "Red",
    price: 219900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: true,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-80",
    name: "Emerald Green Cotton Saree with Gold Dot Jacquard",
    slug: "emerald-green-cotton-saree-with-gold-dot-jacquard",
    description:
      "A parrot-emerald cotton saree woven with an allover gold dot-diamond jacquard pattern.",
    fabric: "Cotton",
    color: "Emerald Green",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-81",
    name: "Beige Gold Silk Saree with Peacock Brocade",
    slug: "beige-gold-silk-saree-with-peacock-brocade",
    description:
      "A beige-gold silk saree with a dense allover brocade of peacocks and vines — richly ornate festive wear.",
    fabric: "Silk Cotton",
    color: "Beige Gold",
    price: 239900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-82",
    name: "Navy Bronze Silk Saree with Bird Brocade",
    slug: "navy-bronze-silk-saree-with-bird-brocade",
    description:
      "A navy-and-bronze silk saree with a dense allover brocade of birds, grapes and vines in a rich jacquard weave.",
    fabric: "Silk Cotton",
    color: "Navy Bronze",
    price: 249900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-83",
    name: "Teal Green Silk Saree with Bird Brocade",
    slug: "teal-green-silk-saree-with-bird-brocade",
    description:
      "A teal-green silk saree woven with an intricate allover bird-and-vine brocade in a subtle olive-gold tone.",
    fabric: "Silk Cotton",
    color: "Teal Green",
    price: 259900,
    compareAtPrice: 289900,
    category: "silk-cotton-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-84",
    name: "Magenta Silk Saree with Gold Paisley Brocade",
    slug: "magenta-silk-saree-with-gold-paisley-brocade",
    description:
      "A magenta silk saree densely woven with a Banarasi-style gold paisley-and-floral brocade.",
    fabric: "Silk Cotton",
    color: "Magenta",
    price: 269900,
    compareAtPrice: null,
    category: "silk-cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-85",
    name: "Teal Cotton Saree with Gold Temple Border",
    slug: "teal-cotton-saree-with-gold-temple-border",
    description:
      "A teal cotton saree with a gold dot-check jacquard body, finished with a gold temple-triangle border.",
    fabric: "Cotton",
    color: "Teal",
    price: 279900,
    compareAtPrice: null,
    category: "cotton-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-86",
    name: "Aubergine Silk Saree with Gold Bird Brocade",
    slug: "aubergine-silk-saree-with-gold-bird-brocade",
    description:
      "A deep aubergine silk saree with an ornate allover gold bird-and-vine brocade weave.",
    fabric: "Silk Cotton",
    color: "Aubergine",
    price: 169900,
    compareAtPrice: 199900,
    category: "silk-cotton-sarees",
    featured: true,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-87",
    name: "Mustard Bandhani Print Cotton Saree",
    slug: "mustard-bandhani-print-cotton-saree",
    description:
      "A mustard cotton saree hand-printed with classic bandhani paisley and check-dot motifs, edged with a triangle border.",
    fabric: "Cotton",
    color: "Mustard",
    price: 179900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-88",
    name: "Navy Batik Print Cotton Saree with Gold Paisley Border",
    slug: "navy-batik-print-cotton-saree-with-gold-paisley-border",
    description:
      "A navy cotton saree in a batik diamond-lattice print with a floral rosette motif, finished with a gold paisley border.",
    fabric: "Cotton",
    color: "Navy Blue",
    price: 189900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-89",
    name: "Peacock Blue Batik Print Cotton Saree with Gold Border",
    slug: "peacock-blue-batik-print-cotton-saree-with-gold-border",
    description:
      "A peacock-blue batik print cotton saree with a triangle lattice and floral motif, bordered in gold and navy.",
    fabric: "Cotton",
    color: "Peacock Blue",
    price: 199900,
    compareAtPrice: 229900,
    category: "printed-sarees",
    featured: false,
    images: 3,
    ext: "jpg",
  },
  {
    folder: "niy-90",
    name: "Emerald Bandhani Print Cotton Saree with Gold Border",
    slug: "emerald-bandhani-print-cotton-saree-with-gold-border",
    description:
      "An emerald-green bandhani print cotton saree with floral rosette motifs and a gold paisley border, finished with matching tassels.",
    fabric: "Cotton",
    color: "Emerald Green",
    price: 209900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-91",
    name: "Plum Batik Print Cotton Saree with Mustard Border",
    slug: "plum-batik-print-cotton-saree-with-mustard-border",
    description:
      "A deep plum batik print cotton saree with lace-doily rosette motifs and a mustard-gold chevron border patch.",
    fabric: "Cotton",
    color: "Plum",
    price: 219900,
    compareAtPrice: null,
    category: "printed-sarees",
    featured: false,
    images: 2,
    ext: "jpg",
  },
  {
    folder: "niy-92",
    name: "Olive Grey Cotton Saree with Navy Floral Border",
    slug: "olive-grey-cotton-saree-with-navy-floral-border",
    description:
      "An olive-grey cotton saree with an allover floral jacquard weave, finished with a navy pallu border.",
    fabric: "Cotton",
    color: "Olive Grey",
    price: 229900,
    compareAtPrice: 259900,
    category: "cotton-sarees",
    featured: false,
    images: 1,
    ext: "jpg",
  },
];

async function main() {
  console.log("Seeding categories...");
  const categoryMap = new Map<string, string>();
  for (const c of categories) {
    const cat = await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name, description: c.description },
      create: c,
    });
    categoryMap.set(c.slug, cat.id);
  }

  console.log("Seeding products...");
  for (const p of products) {
    const ext = p.ext ?? "png";
    const order = p.imageOrder ?? Array.from({ length: p.images }, (_, i) => i + 1);
    const images = order.map((n) => `/images/products/${p.folder}/photo-${n}.${ext}`);
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        description: p.description,
        fabric: p.fabric,
        color: p.color,
        price: p.price,
        compareAtPrice: p.compareAtPrice ?? null,
        images: JSON.stringify(images),
        featured: p.featured,
        categoryId: categoryMap.get(p.category)!,
      },
      create: {
        name: p.name,
        slug: p.slug,
        description: p.description,
        fabric: p.fabric,
        color: p.color,
        price: p.price,
        compareAtPrice: p.compareAtPrice ?? null,
        stock: 15,
        images: JSON.stringify(images),
        featured: p.featured,
        categoryId: categoryMap.get(p.category)!,
      },
    });
  }

  console.log("Seeding users...");
  const adminPassword = await bcrypt.hash("admin123", 10);
  await prisma.user.upsert({
    where: { email: "admin@saree.shop" },
    update: {},
    create: {
      name: "Store Admin",
      email: "admin@saree.shop",
      passwordHash: adminPassword,
      role: "ADMIN",
    },
  });

  const customerPassword = await bcrypt.hash("customer123", 10);
  await prisma.user.upsert({
    where: { email: "customer@example.com" },
    update: {},
    create: {
      name: "Demo Customer",
      email: "customer@example.com",
      passwordHash: customerPassword,
      role: "CUSTOMER",
    },
  });

  console.log("Seed complete.");
  console.log("Admin login: admin@saree.shop / admin123");
  console.log("Customer login: customer@example.com / customer123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
